# Generated by Django 5.0 on 2024-01-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voting_images/'),
        ),
    ]
