# Generated by Django 5.0 on 2024-01-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
